---
- name: "Set up sj dev machine"
  hosts: localhost
  connection: local
  tasks:
    - name: "Create .vimrc file in sj user $HOME"
      template:
        src: "templates/vimrc.j2"
        dest: "/home/sj/.vimrc"
    - name: "Get powerlevel10k from Github"
      git:
        dest: "/home/sj/powerlevel10k"
        depth: 1
        repo: "https://github.com/romkatv/powerlevel10k.git"
    - name: "Create .zshrc file in sj user $HOME"
      template:
        src: "templates/zshrc.j2"
        dest: "/home/sj/.zshrc"
    - name: "Install useful packages"
      become: yes
      package:
        name:
          - jq
          - vlc
          - k4dirstat
          - discord
        state: installed
